#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_width         0
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_modifier mod1
bspc config focus_follows_pointer on

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Nemo state=floating

setxkbmap br,us -option grp:win_space_toggle &
/usr/lib/cinnamon-settings-daemon/csd-mouse &
pipewire &
pipewire-pulse &
pipewire-media-session &
sleep 0.2
$HOME/.config/polybar/launch.sh &
picom &
flashfocus &
wal -R &
xsetroot -cursor_name left_ptr &
gnome-keyring-daemon --start --components=secrets &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
xset r rate 300 50 &
ipfs daemon &
